// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(string2 string) (Event, error) {
	message := NewMessage(string2)
	greater := NewGreater(message)
	event := NewEvent(greater)
	return event, nil
}
